[project]
name = "gitstory"
version = "0.0.1"
description = "GitStory (IDK the Capitalization) is amazing, I think"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
]
