# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Altered python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Where is this occuring again???
      run: |
        ls
    - name: Install uv based on version declared in uv.toml
      uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"
    - name: Install tox. Duh
      run: |
        uv tool install --python-preference only-managed --python 3.14 tox --with tox-uv --with tox-gh
    - name: Hit it with the tox suite
      run: |
        tox
